name: Isolated tests

on:
    schedule:
        - cron: 0 13 * * MON,THU

permissions: read-all

jobs:
    tests:
        name: Isolated tests
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer bin isolated-tests install --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit --extensions Contao\\CoreBundle\\Tests\\PhpunitExtension\\GlobalStateWatcher --colors=always

            - name: Run the unit tests isolated
              run: tools/isolated-tests/bin/run-tests-isolated --ansi
